# Generated by Django 5.0.1 on 2024-04-26 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCategory',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('uuid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=164, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.blockcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlockFlow',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=65)),
                ('flow_type', models.CharField(max_length=30)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.blocktype')),
            ],
        ),
    ]
