# Generated by Django 5.0.1 on 2024-04-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockflow',
            name='is_input',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
