# Generated by Django 5.0.1 on 2024-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_flowchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvastoken',
            name='api_url',
            field=models.URLField(default='https://canvas.clarku.edu'),
            preserve_default=False,
        ),
    ]
