# Generated by Django 5.0.1 on 2024-04-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_canvastoken_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='last_edit',
            field=models.DateTimeField(null=True),
        ),
    ]
