# Generated by Django 5.0.1 on 2024-04-26 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_flowchart_last_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeId',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_in_flowchart_id', models.CharField(max_length=128)),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.flowchart')),
            ],
            options={
                'unique_together': {('flowchart', 'block_in_flowchart_id')},
            },
        ),
    ]
