# Generated by Django 5.0.1 on 2024-04-26 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_qrcodeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowInstanceState',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField()),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.flowchart')),
            ],
        ),
    ]
