# Generated by Django 5.0.1 on 2024-04-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_attendancedaypolyfillrecordings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedaypolyfillrecordings',
            name='by_flowchart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.flowchart'),
        ),
    ]
